# Generated by Django 5.0.3 on 2024-03-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Estoque',
        ),
    ]
