# Generated by Django 5.0.3 on 2024-03-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_created_date_estoque_data_retirada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
