# Generated by Django 5.0.3 on 2024-03-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_estoque_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='motivo_saida',
        ),
        migrations.AddField(
            model_name='estoque',
            name='sala_laboratorio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
