# Generated by Django 5.0.3 on 2024-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_estoque_motivo_saida_estoque_sala_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(max_length=50),
        ),
    ]
