# Generated by Django 5.0.3 on 2024-03-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_historicalestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
