# Generated by Django 5.0.3 on 2024-03-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_estoque_historicalestoque_delete_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='quantidade',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='historicalestoque',
            old_name='quantidade',
            new_name='estoque',
        ),
        migrations.AddField(
            model_name='estoque',
            name='retirada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalestoque',
            name='retirada',
            field=models.IntegerField(default=0),
        ),
    ]
