# Generated by Django 5.0.3 on 2024-03-06 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_estoqueat_historicalestoqueat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estoqueat',
            new_name='Estoque_da_at',
        ),
        migrations.RenameModel(
            old_name='HistoricalEstoqueat',
            new_name='HistoricalEstoque_da_at',
        ),
        migrations.AlterModelOptions(
            name='historicalestoque_da_at',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical estoque_da_at', 'verbose_name_plural': 'historical estoque_da_ats'},
        ),
    ]
