# Generated by Django 5.0.3 on 2024-03-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_estoqueat_estoque_da_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='data_retirada',
            new_name='data_estoque',
        ),
        migrations.RenameField(
            model_name='estoque_da_at',
            old_name='data_retirada',
            new_name='data_estoque',
        ),
        migrations.RenameField(
            model_name='historicalestoque',
            old_name='data_retirada',
            new_name='data_estoque',
        ),
        migrations.RenameField(
            model_name='historicalestoque_da_at',
            old_name='data_retirada',
            new_name='data_estoque',
        ),
    ]
