# Generated by Django 5.0.3 on 2024-03-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_rename_data_retirada_estoque_data_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_da_at',
            name='sala_laboratorio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalestoque_da_at',
            name='sala_laboratorio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
