# Generated by Django 5.0.3 on 2024-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_estoque_da_at_sala_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_da_at',
            name='sala_laboratorio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalestoque_da_at',
            name='sala_laboratorio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
