# Generated by Django 5.0.3 on 2024-03-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_estoque_da_at_sala_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='sala_laboratorio',
            field=models.CharField(blank=True, choices=[('sala1', 'Sala 1'), ('sala2', 'Sala 2'), ('sala3', 'Sala 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalestoque',
            name='sala_laboratorio',
            field=models.CharField(blank=True, choices=[('sala1', 'Sala 1'), ('sala2', 'Sala 2'), ('sala3', 'Sala 3')], max_length=20),
        ),
    ]
