# Generated by Django 5.0.3 on 2024-03-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_estoque_sala_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='sala_laboratorio',
            field=models.SlugField(blank=True, choices=[('a', 'd'), ('b', 'e'), ('c', 'f')]),
        ),
        migrations.AlterField(
            model_name='historicalestoque',
            name='sala_laboratorio',
            field=models.SlugField(blank=True, choices=[('a', 'd'), ('b', 'e'), ('c', 'f')]),
        ),
    ]
