# Generated by Django 5.0.6 on 2024-05-21 15:49

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=253)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sala_laboratorio', models.CharField(blank=True, choices=[('SALA 1.1.03', 'SALA 1.1.03'), ('SALA 1.1.04', 'SALA 1.1.04'), ('SALA 1.1.05', 'SALA 1.1.05'), ('Laboratório de H&P', 'Laboratório de H&P'), ('Laboratório Telecomunicações', 'Laboratório Telecomunicações'), ('Laboratório de Robótica', 'Laboratório de Robótica'), ('Laboratório de Sistemas Digitais', 'Laboratório de Sistemas Digitais'), ('Laboratório BIM', 'Laboratório BIM'), ('Laboratório CAX', 'Laboratório CAX'), ('Laboratório de Eletrônica', 'Laboratório de Eletrônica'), ('Laboratório de Informática 1', 'Laboratório de Informática 1'), ('Laboratório de Informática 2', 'Laboratório de Informática 2'), ('Laboratório de Informática 3', 'Laboratório de Informática 3'), ('Laboratório de Programação Avançada', 'Laboratório de Programação Avançada'), ('Laboratório Cyber', 'Laboratório Cyber'), ('SALA 2.1.01', 'SALA 2.1.01'), ('SALA 2.1.02', 'SALA 2.1.02'), ('SALA 2.1.03', 'SALA 2.1.03'), ('SALA 2.1.04', 'SALA 2.1.04'), ('SALA 2.1.06', 'SALA 2.1.06'), ('SALA 2.1.07', 'SALA 2.1.07'), ('SALA 2.1.08', 'SALA 2.1.08'), ('SALA 2.1.09', 'SALA 2.1.09'), ('SALA 2.2.01', 'SALA 2.2.01'), ('SALA 2.2.02', 'SALA 2.2.02'), ('SALA 2.2.03', 'SALA 2.2.03'), ('SALA 2.2.04', 'SALA 2.2.04'), ('SALA 2.2.05', 'SALA 2.2.05'), ('SALA 2.2.06', 'SALA 2.2.06'), ('SALA 2.2.08', 'SALA 2.2.08'), ('SALA 2.2.09', 'SALA 2.2.09'), ('SALA 2.2.10', 'SALA 2.2.10'), ('SALA 2.3.01 (AUDITÓRIO)', 'SALA 2.3.01 (AUDITÓRIO)'), ('SALA 2.3.03', 'SALA 2.3.03'), ('SALA 2.3.09 (AUDITÓRIO)', 'SALA 2.3.09 (AUDITÓRIO)'), ('SALA 2.3.05', 'SALA 2.3.05'), ('SALA 2.3.06', 'SALA 2.3.06'), ('Laboratório de Simulação Numérica', 'Laboratório de Simulação Numérica'), ('Laboratório de Redes', 'Laboratório de Redes'), ('Laboratório de Software', 'Laboratório de Software'), ('Laboratório de Equipamentos Industriais', 'Laboratório de Equipamentos Industriais'), ('Laboratório de Gestão Empresarial', 'Laboratório de Gestão Empresarial'), ('Laboratório de Transporte e Distribuição', 'Laboratório de Transporte e Distribuição'), ('SALA 4.1.1', 'SALA 4.1.1'), ('SALA 4.1.2', 'SALA 4.1.2'), ('SALA 4.1.3', 'SALA 4.1.3'), ('SALA 4.1.4', 'SALA 4.1.4'), ('SALA 4.1.5', 'SALA 4.1.5'), ('SALA 4.1.6', 'SALA 4.1.6'), ('SALA 4.1.7', 'SALA 4.1.7'), ('SALA 4.1.8', 'SALA 4.1.8'), ('SALA 5.4.1', 'SALA 5.4.1'), ('SALA 5.4.2', 'SALA 5.4.2'), ('SALA 5.4.3', 'SALA 5.4.3'), ('SALA 5.4.4', 'SALA 5.4.4'), ('SALA 5.4.5', 'SALA 5.4.5'), ('SALA 5.4.6', 'SALA 5.4.6'), ('SALA 5.4.7', 'SALA 5.4.7'), ('SALA 5.4.8', 'SALA 5.4.8'), ('SALA 5.4.9', 'SALA 5.4.9'), ('SALA 5.4.10', 'SALA 5.4.10'), ('SALA 5.4.11', 'SALA 5.4.11'), ('SALA 5.4.12', 'SALA 5.4.12'), ('SALA 5.4.13', 'SALA 5.4.12'), ('SALA 5.4.14', 'SALA 5.4.14'), ('SALA 5.4.15', 'SALA 5.4.15'), ('ASSISTÊNCIA TÉCNICA', 'ASSISTÊNCIA TÉCNICA'), ('DEMANDA CORPORATIVA', 'DEMANDA CORPORATIVA')], max_length=50)),
                ('foto', models.ImageField(blank=True, default='caminho_para_a_imagem.jpg', null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('retirada', models.IntegerField(default=0)),
                ('estoque', models.IntegerField()),
                ('data_estoque', models.DateTimeField(default=django.utils.timezone.now)),
                ('sala_laboratorio', models.CharField(blank=True, choices=[('SALA 1.1.03', 'SALA 1.1.03'), ('SALA 1.1.04', 'SALA 1.1.04'), ('SALA 1.1.05', 'SALA 1.1.05'), ('Laboratório de H&P', 'Laboratório de H&P'), ('Laboratório Telecomunicações', 'Laboratório Telecomunicações'), ('Laboratório de Robótica', 'Laboratório de Robótica'), ('Laboratório de Sistemas Digitais', 'Laboratório de Sistemas Digitais'), ('Laboratório BIM', 'Laboratório BIM'), ('Laboratório CAX', 'Laboratório CAX'), ('Laboratório de Eletrônica', 'Laboratório de Eletrônica'), ('Laboratório de Informática 1', 'Laboratório de Informática 1'), ('Laboratório de Informática 2', 'Laboratório de Informática 2'), ('Laboratório de Informática 3', 'Laboratório de Informática 3'), ('Laboratório de Programação Avançada', 'Laboratório de Programação Avançada'), ('Laboratório Cyber', 'Laboratório Cyber'), ('SALA 2.1.01', 'SALA 2.1.01'), ('SALA 2.1.02', 'SALA 2.1.02'), ('SALA 2.1.03', 'SALA 2.1.03'), ('SALA 2.1.04', 'SALA 2.1.04'), ('SALA 2.1.06', 'SALA 2.1.06'), ('SALA 2.1.07', 'SALA 2.1.07'), ('SALA 2.1.08', 'SALA 2.1.08'), ('SALA 2.1.09', 'SALA 2.1.09'), ('SALA 2.2.01', 'SALA 2.2.01'), ('SALA 2.2.02', 'SALA 2.2.02'), ('SALA 2.2.03', 'SALA 2.2.03'), ('SALA 2.2.04', 'SALA 2.2.04'), ('SALA 2.2.05', 'SALA 2.2.05'), ('SALA 2.2.06', 'SALA 2.2.06'), ('SALA 2.2.08', 'SALA 2.2.08'), ('SALA 2.2.09', 'SALA 2.2.09'), ('SALA 2.2.10', 'SALA 2.2.10'), ('SALA 2.3.01 (AUDITÓRIO)', 'SALA 2.3.01 (AUDITÓRIO)'), ('SALA 2.3.03', 'SALA 2.3.03'), ('SALA 2.3.09 (AUDITÓRIO)', 'SALA 2.3.09 (AUDITÓRIO)'), ('SALA 2.3.05', 'SALA 2.3.05'), ('SALA 2.3.06', 'SALA 2.3.06'), ('Laboratório de Simulação Numérica', 'Laboratório de Simulação Numérica'), ('Laboratório de Redes', 'Laboratório de Redes'), ('Laboratório de Software', 'Laboratório de Software'), ('Laboratório de Equipamentos Industriais', 'Laboratório de Equipamentos Industriais'), ('Laboratório de Gestão Empresarial', 'Laboratório de Gestão Empresarial'), ('Laboratório de Transporte e Distribuição', 'Laboratório de Transporte e Distribuição'), ('SALA 4.1.1', 'SALA 4.1.1'), ('SALA 4.1.2', 'SALA 4.1.2'), ('SALA 4.1.3', 'SALA 4.1.3'), ('SALA 4.1.4', 'SALA 4.1.4'), ('SALA 4.1.5', 'SALA 4.1.5'), ('SALA 4.1.6', 'SALA 4.1.6'), ('SALA 4.1.7', 'SALA 4.1.7'), ('SALA 4.1.8', 'SALA 4.1.8'), ('SALA 5.4.1', 'SALA 5.4.1'), ('SALA 5.4.2', 'SALA 5.4.2'), ('SALA 5.4.3', 'SALA 5.4.3'), ('SALA 5.4.4', 'SALA 5.4.4'), ('SALA 5.4.5', 'SALA 5.4.5'), ('SALA 5.4.6', 'SALA 5.4.6'), ('SALA 5.4.7', 'SALA 5.4.7'), ('SALA 5.4.8', 'SALA 5.4.8'), ('SALA 5.4.9', 'SALA 5.4.9'), ('SALA 5.4.10', 'SALA 5.4.10'), ('SALA 5.4.11', 'SALA 5.4.11'), ('SALA 5.4.12', 'SALA 5.4.12'), ('SALA 5.4.13', 'SALA 5.4.12'), ('SALA 5.4.14', 'SALA 5.4.14'), ('SALA 5.4.15', 'SALA 5.4.15'), ('ASSISTÊNCIA TÉCNICA', 'ASSISTÊNCIA TÉCNICA'), ('DEMANDA CORPORATIVA', 'DEMANDA CORPORATIVA')], max_length=50)),
                ('foto', models.ImageField(blank=True, default='caminho_para_a_imagem.jpg', upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDemanda',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=253)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sala_laboratorio', models.CharField(blank=True, choices=[('SALA 1.1.03', 'SALA 1.1.03'), ('SALA 1.1.04', 'SALA 1.1.04'), ('SALA 1.1.05', 'SALA 1.1.05'), ('Laboratório de H&P', 'Laboratório de H&P'), ('Laboratório Telecomunicações', 'Laboratório Telecomunicações'), ('Laboratório de Robótica', 'Laboratório de Robótica'), ('Laboratório de Sistemas Digitais', 'Laboratório de Sistemas Digitais'), ('Laboratório BIM', 'Laboratório BIM'), ('Laboratório CAX', 'Laboratório CAX'), ('Laboratório de Eletrônica', 'Laboratório de Eletrônica'), ('Laboratório de Informática 1', 'Laboratório de Informática 1'), ('Laboratório de Informática 2', 'Laboratório de Informática 2'), ('Laboratório de Informática 3', 'Laboratório de Informática 3'), ('Laboratório de Programação Avançada', 'Laboratório de Programação Avançada'), ('Laboratório Cyber', 'Laboratório Cyber'), ('SALA 2.1.01', 'SALA 2.1.01'), ('SALA 2.1.02', 'SALA 2.1.02'), ('SALA 2.1.03', 'SALA 2.1.03'), ('SALA 2.1.04', 'SALA 2.1.04'), ('SALA 2.1.06', 'SALA 2.1.06'), ('SALA 2.1.07', 'SALA 2.1.07'), ('SALA 2.1.08', 'SALA 2.1.08'), ('SALA 2.1.09', 'SALA 2.1.09'), ('SALA 2.2.01', 'SALA 2.2.01'), ('SALA 2.2.02', 'SALA 2.2.02'), ('SALA 2.2.03', 'SALA 2.2.03'), ('SALA 2.2.04', 'SALA 2.2.04'), ('SALA 2.2.05', 'SALA 2.2.05'), ('SALA 2.2.06', 'SALA 2.2.06'), ('SALA 2.2.08', 'SALA 2.2.08'), ('SALA 2.2.09', 'SALA 2.2.09'), ('SALA 2.2.10', 'SALA 2.2.10'), ('SALA 2.3.01 (AUDITÓRIO)', 'SALA 2.3.01 (AUDITÓRIO)'), ('SALA 2.3.03', 'SALA 2.3.03'), ('SALA 2.3.09 (AUDITÓRIO)', 'SALA 2.3.09 (AUDITÓRIO)'), ('SALA 2.3.05', 'SALA 2.3.05'), ('SALA 2.3.06', 'SALA 2.3.06'), ('Laboratório de Simulação Numérica', 'Laboratório de Simulação Numérica'), ('Laboratório de Redes', 'Laboratório de Redes'), ('Laboratório de Software', 'Laboratório de Software'), ('Laboratório de Equipamentos Industriais', 'Laboratório de Equipamentos Industriais'), ('Laboratório de Gestão Empresarial', 'Laboratório de Gestão Empresarial'), ('Laboratório de Transporte e Distribuição', 'Laboratório de Transporte e Distribuição'), ('SALA 4.1.1', 'SALA 4.1.1'), ('SALA 4.1.2', 'SALA 4.1.2'), ('SALA 4.1.3', 'SALA 4.1.3'), ('SALA 4.1.4', 'SALA 4.1.4'), ('SALA 4.1.5', 'SALA 4.1.5'), ('SALA 4.1.6', 'SALA 4.1.6'), ('SALA 4.1.7', 'SALA 4.1.7'), ('SALA 4.1.8', 'SALA 4.1.8'), ('SALA 5.4.1', 'SALA 5.4.1'), ('SALA 5.4.2', 'SALA 5.4.2'), ('SALA 5.4.3', 'SALA 5.4.3'), ('SALA 5.4.4', 'SALA 5.4.4'), ('SALA 5.4.5', 'SALA 5.4.5'), ('SALA 5.4.6', 'SALA 5.4.6'), ('SALA 5.4.7', 'SALA 5.4.7'), ('SALA 5.4.8', 'SALA 5.4.8'), ('SALA 5.4.9', 'SALA 5.4.9'), ('SALA 5.4.10', 'SALA 5.4.10'), ('SALA 5.4.11', 'SALA 5.4.11'), ('SALA 5.4.12', 'SALA 5.4.12'), ('SALA 5.4.13', 'SALA 5.4.12'), ('SALA 5.4.14', 'SALA 5.4.14'), ('SALA 5.4.15', 'SALA 5.4.15'), ('ASSISTÊNCIA TÉCNICA', 'ASSISTÊNCIA TÉCNICA'), ('DEMANDA CORPORATIVA', 'DEMANDA CORPORATIVA')], max_length=50)),
                ('foto', models.TextField(blank=True, default='caminho_para_a_imagem.jpg', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical demanda',
                'verbose_name_plural': 'historical demandas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEstoque',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('nome', models.CharField(max_length=50)),
                ('retirada', models.IntegerField(default=0)),
                ('estoque', models.IntegerField()),
                ('data_estoque', models.DateTimeField(default=django.utils.timezone.now)),
                ('sala_laboratorio', models.CharField(blank=True, choices=[('SALA 1.1.03', 'SALA 1.1.03'), ('SALA 1.1.04', 'SALA 1.1.04'), ('SALA 1.1.05', 'SALA 1.1.05'), ('Laboratório de H&P', 'Laboratório de H&P'), ('Laboratório Telecomunicações', 'Laboratório Telecomunicações'), ('Laboratório de Robótica', 'Laboratório de Robótica'), ('Laboratório de Sistemas Digitais', 'Laboratório de Sistemas Digitais'), ('Laboratório BIM', 'Laboratório BIM'), ('Laboratório CAX', 'Laboratório CAX'), ('Laboratório de Eletrônica', 'Laboratório de Eletrônica'), ('Laboratório de Informática 1', 'Laboratório de Informática 1'), ('Laboratório de Informática 2', 'Laboratório de Informática 2'), ('Laboratório de Informática 3', 'Laboratório de Informática 3'), ('Laboratório de Programação Avançada', 'Laboratório de Programação Avançada'), ('Laboratório Cyber', 'Laboratório Cyber'), ('SALA 2.1.01', 'SALA 2.1.01'), ('SALA 2.1.02', 'SALA 2.1.02'), ('SALA 2.1.03', 'SALA 2.1.03'), ('SALA 2.1.04', 'SALA 2.1.04'), ('SALA 2.1.06', 'SALA 2.1.06'), ('SALA 2.1.07', 'SALA 2.1.07'), ('SALA 2.1.08', 'SALA 2.1.08'), ('SALA 2.1.09', 'SALA 2.1.09'), ('SALA 2.2.01', 'SALA 2.2.01'), ('SALA 2.2.02', 'SALA 2.2.02'), ('SALA 2.2.03', 'SALA 2.2.03'), ('SALA 2.2.04', 'SALA 2.2.04'), ('SALA 2.2.05', 'SALA 2.2.05'), ('SALA 2.2.06', 'SALA 2.2.06'), ('SALA 2.2.08', 'SALA 2.2.08'), ('SALA 2.2.09', 'SALA 2.2.09'), ('SALA 2.2.10', 'SALA 2.2.10'), ('SALA 2.3.01 (AUDITÓRIO)', 'SALA 2.3.01 (AUDITÓRIO)'), ('SALA 2.3.03', 'SALA 2.3.03'), ('SALA 2.3.09 (AUDITÓRIO)', 'SALA 2.3.09 (AUDITÓRIO)'), ('SALA 2.3.05', 'SALA 2.3.05'), ('SALA 2.3.06', 'SALA 2.3.06'), ('Laboratório de Simulação Numérica', 'Laboratório de Simulação Numérica'), ('Laboratório de Redes', 'Laboratório de Redes'), ('Laboratório de Software', 'Laboratório de Software'), ('Laboratório de Equipamentos Industriais', 'Laboratório de Equipamentos Industriais'), ('Laboratório de Gestão Empresarial', 'Laboratório de Gestão Empresarial'), ('Laboratório de Transporte e Distribuição', 'Laboratório de Transporte e Distribuição'), ('SALA 4.1.1', 'SALA 4.1.1'), ('SALA 4.1.2', 'SALA 4.1.2'), ('SALA 4.1.3', 'SALA 4.1.3'), ('SALA 4.1.4', 'SALA 4.1.4'), ('SALA 4.1.5', 'SALA 4.1.5'), ('SALA 4.1.6', 'SALA 4.1.6'), ('SALA 4.1.7', 'SALA 4.1.7'), ('SALA 4.1.8', 'SALA 4.1.8'), ('SALA 5.4.1', 'SALA 5.4.1'), ('SALA 5.4.2', 'SALA 5.4.2'), ('SALA 5.4.3', 'SALA 5.4.3'), ('SALA 5.4.4', 'SALA 5.4.4'), ('SALA 5.4.5', 'SALA 5.4.5'), ('SALA 5.4.6', 'SALA 5.4.6'), ('SALA 5.4.7', 'SALA 5.4.7'), ('SALA 5.4.8', 'SALA 5.4.8'), ('SALA 5.4.9', 'SALA 5.4.9'), ('SALA 5.4.10', 'SALA 5.4.10'), ('SALA 5.4.11', 'SALA 5.4.11'), ('SALA 5.4.12', 'SALA 5.4.12'), ('SALA 5.4.13', 'SALA 5.4.12'), ('SALA 5.4.14', 'SALA 5.4.14'), ('SALA 5.4.15', 'SALA 5.4.15'), ('ASSISTÊNCIA TÉCNICA', 'ASSISTÊNCIA TÉCNICA'), ('DEMANDA CORPORATIVA', 'DEMANDA CORPORATIVA')], max_length=50)),
                ('foto', models.TextField(blank=True, default='caminho_para_a_imagem.jpg', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical estoque',
                'verbose_name_plural': 'historical estoques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
