# Generated by Django 5.0.3 on 2024-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='sala_laboratorio',
            field=models.CharField(blank=True, choices=[('a', 'd'), ('b', 'e'), ('c', 'f')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalestoque',
            name='sala_laboratorio',
            field=models.CharField(blank=True, choices=[('a', 'd'), ('b', 'e'), ('c', 'f')], max_length=50),
        ),
    ]
