# Generated by Django 5.0.1 on 2024-09-28 16:44

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueAlmo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('retirada', models.IntegerField(default=0)),
                ('estoque', models.IntegerField()),
                ('data_estoque', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(default='caminho_para_a_imagem.jpg', upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEstoqueAlmo',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('nome', models.CharField(max_length=50)),
                ('retirada', models.IntegerField(default=0)),
                ('estoque', models.IntegerField()),
                ('data_estoque', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto', models.TextField(default='caminho_para_a_imagem.jpg', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical estoque almo',
                'verbose_name_plural': 'historical estoque almos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
