# Generated by Django 5.0.6 on 2024-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='foto',
            field=models.ImageField(default='caminho_para_a_imagem.jpg', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='historicalestoque',
            name='foto',
            field=models.TextField(default='caminho_para_a_imagem.jpg', max_length=100),
        ),
    ]
