# Generated by Django 5.1.4 on 2024-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquealmo',
            name='categoria',
            field=models.CharField(choices=[('INF', 'Infra'), ('TI', 'TI')], default='TI', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalestoquealmo',
            name='categoria',
            field=models.CharField(choices=[('INF', 'Infra'), ('TI', 'TI')], default='TI', max_length=3),
        ),
    ]
