# Generated by Django 4.0.6 on 2024-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_estoqueat_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueat',
            name='foto',
            field=models.ImageField(default='caminho_para_a_imagem.jpg', upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='historicalestoqueat',
            name='foto',
            field=models.TextField(default='caminho_para_a_imagem.jpg', max_length=100),
        ),
    ]
