# Generated by Django 5.1.4 on 2024-12-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_estoquealmo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquealmo',
            name='categoria',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('TI', 'TI')], default='TI', max_length=6),
        ),
        migrations.AlterField(
            model_name='historicalestoquealmo',
            name='categoria',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('TI', 'TI')], default='TI', max_length=6),
        ),
    ]
