# Generated by Django 5.0.3 on 2024-03-25 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_demandas_alter_estoque_sala_laboratorio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demandas',
            new_name='Demanda',
        ),
        migrations.RenameModel(
            old_name='HistoricalDemandas',
            new_name='HistoricalDemanda',
        ),
        migrations.AlterModelOptions(
            name='historicaldemanda',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical demanda', 'verbose_name_plural': 'historical demandas'},
        ),
    ]
