# Generated by Django 4.0.6 on 2024-10-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_estoqueat_foto_historicalestoqueat_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquealmo',
            options={'permissions': [('change_estoque_almo', 'Pode editar Estoque Almo')]},
        ),
        migrations.AlterModelOptions(
            name='estoqueat',
            options={'permissions': [('change_estoque_at', 'Pode editar Estoque AT')]},
        ),
    ]
