# Generated by Django 4.0.6 on 2024-10-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_estoquealmo_options_alter_estoqueat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquealmo',
            name='endereco',
            field=models.CharField(default='Sem registro de localização', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalestoquealmo',
            name='endereco',
            field=models.CharField(default='Sem registro de localização', max_length=255),
        ),
    ]
