# Generated by Django 5.0.3 on 2024-03-25 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_demandas_demanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_estoque',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demanda',
            name='sala_laboratorio',
            field=models.CharField(blank=True, choices=[('SALA 1.1.03', 'SALA 1.1.03'), ('SALA 1.1.04', 'SALA 1.1.04'), ('SALA 1.1.05', 'SALA 1.1.05'), ('Laboratório de H&P', 'Laboratório de H&P'), ('Laboratório Telecomunicações', 'Laboratório Telecomunicações'), ('Laboratório de Robótica', 'Laboratório de Robótica'), ('Laboratório de Sistemas Digitais', 'Laboratório de Sistemas Digitais'), ('Laboratório BIM', 'Laboratório BIM'), ('Laboratório CAX', 'Laboratório CAX'), ('Laboratório de Eletrônica', 'Laboratório de Eletrônica'), ('Laboratório de Informática 1', 'Laboratório de Informática 1'), ('Laboratório de Informática 2', 'Laboratório de Informática 2'), ('Laboratório de Informática 3', 'Laboratório de Informática 3'), ('Laboratório de Programação Avançada', 'Laboratório de Programação Avançada'), ('Laboratório Cyber', 'Laboratório Cyber'), ('SALA 2.1.01', 'SALA 2.1.01'), ('SALA 2.1.02', 'SALA 2.1.02'), ('SALA 2.1.03', 'SALA 2.1.03'), ('SALA 2.1.04', 'SALA 2.1.04'), ('SALA 2.1.06', 'SALA 2.1.06'), ('SALA 2.1.07', 'SALA 2.1.07'), ('SALA 2.1.08', 'SALA 2.1.08'), ('SALA 2.1.09', 'SALA 2.1.09'), ('SALA 2.2.01', 'SALA 2.2.01'), ('SALA 2.2.02', 'SALA 2.2.02'), ('SALA 2.2.03', 'SALA 2.2.03'), ('SALA 2.2.04', 'SALA 2.2.04'), ('SALA 2.2.05', 'SALA 2.2.05'), ('SALA 2.2.06', 'SALA 2.2.06'), ('SALA 2.2.08', 'SALA 2.2.08'), ('SALA 2.2.09', 'SALA 2.2.09'), ('SALA 2.2.10', 'SALA 2.2.10'), ('SALA 2.3.01 (AUDITÓRIO)', 'SALA 2.3.01 (AUDITÓRIO)'), ('SALA 2.3.03', 'SALA 2.3.03'), ('SALA 2.3.09 (AUDITÓRIO)', 'SALA 2.3.09 (AUDITÓRIO)'), ('SALA 2.3.05', 'SALA 2.3.05'), ('SALA 2.3.06', 'SALA 2.3.06'), ('Laboratório de Simulação Numérica', 'Laboratório de Simulação Numérica'), ('Laboratório de Redes', 'Laboratório de Redes'), ('Laboratório de Software', 'Laboratório de Software'), ('Laboratório de Equipamentos Industriais', 'Laboratório de Equipamentos Industriais'), ('Laboratório de Gestão Empresarial', 'Laboratório de Gestão Empresarial'), ('Laboratório de Transporte e Distribuição', 'Laboratório de Transporte e Distribuição'), ('SALA 4.1.1', 'SALA 4.1.1'), ('SALA 4.1.2', 'SALA 4.1.2'), ('SALA 4.1.3', 'SALA 4.1.3'), ('SALA 4.1.4', 'SALA 4.1.4'), ('SALA 4.1.5', 'SALA 4.1.5'), ('SALA 4.1.6', 'SALA 4.1.6'), ('SALA 4.1.7', 'SALA 4.1.7'), ('SALA 4.1.8', 'SALA 4.1.8'), ('SALA 5.4.1', 'SALA 5.4.1'), ('SALA 5.4.2', 'SALA 5.4.2'), ('SALA 5.4.3', 'SALA 5.4.3'), ('SALA 5.4.4', 'SALA 5.4.4'), ('SALA 5.4.5', 'SALA 5.4.5'), ('SALA 5.4.6', 'SALA 5.4.6'), ('SALA 5.4.7', 'SALA 5.4.7'), ('SALA 5.4.8', 'SALA 5.4.8'), ('SALA 5.4.9', 'SALA 5.4.9'), ('SALA 5.4.10', 'SALA 5.4.10'), ('SALA 5.4.11', 'SALA 5.4.11'), ('SALA 5.4.12', 'SALA 5.4.12'), ('SALA 5.4.13', 'SALA 5.4.12'), ('SALA 5.4.14', 'SALA 5.4.14'), ('SALA 5.4.15', 'SALA 5.4.15')], max_length=50),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='data_estoque',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='sala_laboratorio',
            field=models.CharField(blank=True, choices=[('SALA 1.1.03', 'SALA 1.1.03'), ('SALA 1.1.04', 'SALA 1.1.04'), ('SALA 1.1.05', 'SALA 1.1.05'), ('Laboratório de H&P', 'Laboratório de H&P'), ('Laboratório Telecomunicações', 'Laboratório Telecomunicações'), ('Laboratório de Robótica', 'Laboratório de Robótica'), ('Laboratório de Sistemas Digitais', 'Laboratório de Sistemas Digitais'), ('Laboratório BIM', 'Laboratório BIM'), ('Laboratório CAX', 'Laboratório CAX'), ('Laboratório de Eletrônica', 'Laboratório de Eletrônica'), ('Laboratório de Informática 1', 'Laboratório de Informática 1'), ('Laboratório de Informática 2', 'Laboratório de Informática 2'), ('Laboratório de Informática 3', 'Laboratório de Informática 3'), ('Laboratório de Programação Avançada', 'Laboratório de Programação Avançada'), ('Laboratório Cyber', 'Laboratório Cyber'), ('SALA 2.1.01', 'SALA 2.1.01'), ('SALA 2.1.02', 'SALA 2.1.02'), ('SALA 2.1.03', 'SALA 2.1.03'), ('SALA 2.1.04', 'SALA 2.1.04'), ('SALA 2.1.06', 'SALA 2.1.06'), ('SALA 2.1.07', 'SALA 2.1.07'), ('SALA 2.1.08', 'SALA 2.1.08'), ('SALA 2.1.09', 'SALA 2.1.09'), ('SALA 2.2.01', 'SALA 2.2.01'), ('SALA 2.2.02', 'SALA 2.2.02'), ('SALA 2.2.03', 'SALA 2.2.03'), ('SALA 2.2.04', 'SALA 2.2.04'), ('SALA 2.2.05', 'SALA 2.2.05'), ('SALA 2.2.06', 'SALA 2.2.06'), ('SALA 2.2.08', 'SALA 2.2.08'), ('SALA 2.2.09', 'SALA 2.2.09'), ('SALA 2.2.10', 'SALA 2.2.10'), ('SALA 2.3.01 (AUDITÓRIO)', 'SALA 2.3.01 (AUDITÓRIO)'), ('SALA 2.3.03', 'SALA 2.3.03'), ('SALA 2.3.09 (AUDITÓRIO)', 'SALA 2.3.09 (AUDITÓRIO)'), ('SALA 2.3.05', 'SALA 2.3.05'), ('SALA 2.3.06', 'SALA 2.3.06'), ('Laboratório de Simulação Numérica', 'Laboratório de Simulação Numérica'), ('Laboratório de Redes', 'Laboratório de Redes'), ('Laboratório de Software', 'Laboratório de Software'), ('Laboratório de Equipamentos Industriais', 'Laboratório de Equipamentos Industriais'), ('Laboratório de Gestão Empresarial', 'Laboratório de Gestão Empresarial'), ('Laboratório de Transporte e Distribuição', 'Laboratório de Transporte e Distribuição'), ('SALA 4.1.1', 'SALA 4.1.1'), ('SALA 4.1.2', 'SALA 4.1.2'), ('SALA 4.1.3', 'SALA 4.1.3'), ('SALA 4.1.4', 'SALA 4.1.4'), ('SALA 4.1.5', 'SALA 4.1.5'), ('SALA 4.1.6', 'SALA 4.1.6'), ('SALA 4.1.7', 'SALA 4.1.7'), ('SALA 4.1.8', 'SALA 4.1.8'), ('SALA 5.4.1', 'SALA 5.4.1'), ('SALA 5.4.2', 'SALA 5.4.2'), ('SALA 5.4.3', 'SALA 5.4.3'), ('SALA 5.4.4', 'SALA 5.4.4'), ('SALA 5.4.5', 'SALA 5.4.5'), ('SALA 5.4.6', 'SALA 5.4.6'), ('SALA 5.4.7', 'SALA 5.4.7'), ('SALA 5.4.8', 'SALA 5.4.8'), ('SALA 5.4.9', 'SALA 5.4.9'), ('SALA 5.4.10', 'SALA 5.4.10'), ('SALA 5.4.11', 'SALA 5.4.11'), ('SALA 5.4.12', 'SALA 5.4.12'), ('SALA 5.4.13', 'SALA 5.4.12'), ('SALA 5.4.14', 'SALA 5.4.14'), ('SALA 5.4.15', 'SALA 5.4.15')], max_length=50),
        ),
    ]
