# Generated by Django 5.0.3 on 2024-04-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_demanda_data_estoque_demanda_sala_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='foto',
            field=models.ImageField(default='caminho_para_a_imagem.jpg', upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='foto',
            field=models.TextField(default='caminho_para_a_imagem.jpg', max_length=100),
        ),
    ]
