# Generated by Django 4.0.6 on 2024-10-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_estoquealmo_endereco_historicalestoquealmo_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estoquealmo',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estoqueat',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalestoque',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalestoquealmo',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalestoqueat',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EstoqueHistoricoAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_adicionada', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.estoqueat')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueHistoricoAlmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_adicionada', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.estoquealmo')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_adicionada', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.estoque')),
            ],
        ),
    ]
