# Generated by Django 4.0.6 on 2024-12-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_estoque_adicao_estoquealmo_adicao_estoqueat_adicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='categoria',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('TI', 'TI')], default='TI', max_length=6),
        ),
        migrations.AddField(
            model_name='historicalestoque',
            name='categoria',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('TI', 'TI')], default='TI', max_length=6),
        ),
    ]
