# Generated by Django 5.0.3 on 2024-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_demanda_foto_historicaldemanda_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(max_length=253),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='descricao',
            field=models.TextField(max_length=253),
        ),
    ]
