# Generated by Django 5.1.1 on 2024-10-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_estoquehistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquealmo',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estoqueat',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalestoquealmo',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalestoqueat',
            name='adicao',
            field=models.IntegerField(default=0),
        ),
    ]
