# Generated by Django 4.0.6 on 2024-12-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_estoque_categoria_historicalestoque_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='historicalestoque',
            name='categoria',
        ),
    ]
