# Generated by Django 4.0.6 on 2024-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_estoque_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquealmo',
            name='categoria',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('TI', 'TI')], default='TI', max_length=6),
        ),
        migrations.AddField(
            model_name='historicalestoquealmo',
            name='categoria',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('TI', 'TI')], default='TI', max_length=6),
        ),
    ]
