# Generated by Django 5.1.4 on 2024-12-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_estoque_foto_alter_historicalestoque_foto'),
        ('polls', '0008_estoquehistoricoalmo_estoquehistoricoat'),
    ]

    operations = [
    ]
