# Generated by Django 5.1.5 on 2025-03-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_estoquealmo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquealmo',
            name='modelo',
            field=models.CharField(default='Nenhum', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalestoquealmo',
            name='modelo',
            field=models.CharField(default='Nenhum', max_length=255),
        ),
    ]
