# Generated by Django 5.1.5 on 2025-03-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_estoquealmo_modelo_historicalestoquealmo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquealmo',
            name='categoria',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('TI', 'TI'), ('OBRA', 'OBRA')], default='TI', max_length=6),
        ),
        migrations.AlterField(
            model_name='historicalestoquealmo',
            name='categoria',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('TI', 'TI'), ('OBRA', 'OBRA')], default='TI', max_length=6),
        ),
    ]
