# Generated by Django 5.2.1 on 2025-05-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_estoquealmo_tipo_historicalestoquealmo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquealmo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalestoquealmo',
            name='tipo',
        ),
    ]
