# Generated by Django 5.2.1 on 2025-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_estoquealmo_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquealmo',
            name='tipo',
            field=models.CharField(default='Nenhuma', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalestoquealmo',
            name='tipo',
            field=models.CharField(default='Nenhuma', max_length=255),
        ),
    ]
